### ISSUE TITLE
Can't import noise from other directories

### ISSUE THREAD

**Issue by Sondsara** [caseman/noise#13]
Heyo, I'm a bit of a python noob, so forgive me if I'm doing something wrong here. When I run python from the repo directory, I can import noise without a problem. When I go up a level, I get this: 

>>> import noise
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "noise/__init__.py", line 12, in <module>
    from . import _perlin, _simplex
ImportError: cannot import name _perlin

It can find the noise script just fine, but the noise script can't find perlin and simplex files? Not sure what the fix is for this - it's probably pretty simple but I couldn't find anything on it.

Thanks!

**Comment by brycepg** [comment]
What's happening is that python prefers to look in relative paths before absolute paths. Since you can import noise from the repo directory, that means it's probably already in your python path.

Say this repository lives in `foo/noise/` and now you are in `foo/` if you go up a directory, then python will see that the local directory `noise/` has an `__init__.py` file and try to import the directory instead of the module installed in your python path. Since this module requires the `_noise` and `_simplex` C extensions to be compiled, this wont work.

Remove or rename this repo directory from your project and use pip. If you really want to install from source, run `python setup.py build` to build locally and `python setup.py install` to install into your python path.

**Comment by Sondsara** [comment]
Hey thanks for the detailed response. I originally installed is using `python setup.py install` as you say. Moving it out of the working directory did in fact resolve the issue. Thanks! Quick follow up question though: I also have other modules like caffe, and protobuf in that directory. Why can I import those with no issue?

**Comment by brycepg** [comment]
You're welcome.

`__init__.py` depends on `_perlin` and `_simplex` which are C extensions which get compiled into shared object files. If you did `python setup.py build` and then copied `dist/lib*/*.so` (assuming you're on linux) into the main noise repo directory, then what you are doing would work.
