### ISSUE TITLE
cannot import name _perlin after running install.py successfully from master

### ISSUE THREAD

**Issue by kalexmills** [caseman/noise#21]
$:/mnt/c/Users/kalex/Sanity/mmttrpg/python$ python3
Python 3.4.3 (default, Nov 17 2016, 01:08:31)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import noise
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/kalex/Sanity/mmttrpg/python/noise/__init__.py", line 12, in <module>
    from . import _perlin, _simplex

**Comment by brycepg** [comment]
python3 treats any directory as a package. Because you have a directory called noise, when you call `import noise`. It imports the directory in the current working directory before looking in site-packages (causing this error). You can cd to another directory and `import noise` or move the noise git directory to prevent this module name collision

**Comment by kalexmills** [comment]
That is precisely it! Thanks for helping and for the really quick response. :-)
